### ISSUE TITLE
Gun does not work properly at night

### ISSUE THREAD

**Issue by HalconThule** [SachaOropeza/AH64D-Project#14]
It is not possible to "swing" the gun at night. As CPG the TADS HUD transfers to the HMD and it becomes black-and-white.

Here is a picture about the secound issue:
https://1drv.ms/i/s!AuahdZyIeKdGg95HaRvSU5bp-vhx0g

tested in Multiplayer (dedicated)

RPT:
[arma3_x64_2017-03-22_17-50-55.zip](https://github.com/SachaOropeza/AH64D-v1.43-/files/862951/arma3_x64_2017-03-22_17-50-55.zip)

**Comment by SachaOropeza** [comment]
Have you used MCC while being in the AH-64D ? This addon is known to bug most systems upon usage.

**Comment by SachaOropeza** [comment]
Also, did you pack the .pbo yourself from the GitHub or did you used the latest .pbo ready files ?

**Comment by HalconThule** [comment]
It was the 19/03/2017 Version with .pbo ready files from the Armaholic Frontpage.
MCC Mod was loaded but not used.

**Comment by SachaOropeza** [comment]
Can you reproduce this issue ?

**Comment by SachaOropeza** [comment]
Also, please confirm the bug appears as well on the original v1.43 instead of the v1.43+.

**Comment by HalconThule** [comment]
Yes, the error is also repeated for different players.

To produce the error: Go to a dedicated Server with 2 players (Pilot + CPG). Start the Apache, set the daytime with Zeus on night: error occurs. Reset the daytime to day, error disappears.

**Comment by SachaOropeza** [comment]
As I told you, stay away of Zeus and MCC while being INSIDE the AH-64D. Real time game changers may have undesirable effects on the bird.

Does the issue also happen when you do start the mission with night time ready ?

**Comment by Hajimoto** [comment]
I need to have this clarified if it is the gunners view that displays the issue because the pilot view is fine.

**Comment by Hajimoto** [comment]
We have tested this and the CPG gun view is ALWAYS black and white.  Head tracking of camera view in Pilots seat works with TrackIr but head tracking of Gun in CPG does NOT work with TrackIr only mouse.
The image provided by  HalconThule shows the entire gunners seat view as Balck and White and we are not able to duplicate what is reported/shown

**Comment by SachaOropeza** [comment]
CPG DTV is meant to be black and white, the colored DTV came out years after but it was monochrome on the Block 2.

**Comment by TitansWeasel** [comment]
Hello

HalconThule and me testet this again.
The issue appears just when you change the time with zeus.
When the mission starts already in night everything is ok.

thank you for that great work at this heli!

**Comment by SachaOropeza** [comment]
Fixed.
