### ISSUE TITLE
Any player that enter CPG seat looses Arming Menu

### ISSUE THREAD

**Issue by Hajimoto** [SachaOropeza/AH64D-Project#15]
I have tried in multiple configurations with as many as 3 players:
- Pilots seat = Arming Option
- Pilot outside AH-64 = Arming Option
- New Player to server = Arming Option
- Any of the above enter CPG or Gunners Seat = Loss of Arming Option.
- Existing loss of Arming player disconnects and reconnects to server = No Arming Option

**Server details:**
- Dedicated server ARMA3 v1.68.141112 , 64Bit, 

**Mods:** 
- AH-64D (v1.43+) with revised ahspawns.sqf, ah64d_init.sqf 
- CBA_A3 v3.2.1.170227

**Comment by SachaOropeza** [comment]
I was aware of this bug but I didn't know what was toggling this. The only solution is to completely disconnect and reconnect to the server to allow the Arming Menu to be displayed again as far as I witnessed the issue. I'll dig in it.

**Comment by blindbat2006** [comment]
Believe this to be fixed in https://github.com/blindbat2006/AH64D-v1.43-/commit/df8b9e513e4f8f7df43b58d6fcc2b1d382a55fc0.

Can close now
