### ISSUE TITLE
After rearming weapon selection is inoperable

### ISSUE THREAD

**Issue by Hajimoto** [SachaOropeza/AH64D-Project#17]
After successful loadout selection, weapon selector is inoperable.
See video that captures the event:
https://youtu.be/9LE2nF4QCPI

**Server details:**
Dedicated AH64D TEST Server - ARMA3 v1.68.141112 , 64Bit,

**Mods:**
AH-64D (v1.43+) with revised ahspawns.sqf, ah64d_init.sqf
CBA_A3 v3.2.1.170227

**Comment by SachaOropeza** [comment]
Thanks for reporting. I'll look into that.
