### ISSUE TITLE
Error when cycle left MFD to waypoint mode

### ISSUE THREAD

**Issue by unhappytroll** [SachaOropeza/AH64D-Project#22]
When one cycling left MFD from action menu to waypoint mode this error is opens if no waypoints defined:
http://imgur.com/a/ZgnOj

current master branch, pbo made myself.

**Comment by SachaOropeza** [comment]
This issue is already known and as you stated, you have to set up your navigation route in order to clean it up, or switch into ATK mode.

**Comment by unhappytroll** [comment]
may be it should be enveloped in try-catch.
