### ISSUE TITLE
hell yea i love you guys!

### ISSUE THREAD

**Issue by NeuralBow** [SachaOropeza/AH64D-Project#42]
hello,

no issues yet but i just wanted to thank you all for the work you put into this addon i missed it soo freaking much

waiting for the Apache FCR to be uploaded to armaholic then ill start testing right away!

Thanks again i freaking LOVE you GUYS!!!!

greetings from a Dutch Apache gunner

**Comment by SachaOropeza** [comment]
Thanks man.
