### ISSUE TITLE
Advanced Flight Model engine MFD and control

### ISSUE THREAD

**Issue by mattysmith22** [SachaOropeza/AH64D-Project#48]
The engine MFD page does not accurately display the engine data from the Apache. This is partly because the data is gathered in incorrect scales, and partly due to some areas of the page (Namely the named selection for digits for torque) being malformed on the page. In addition, values do not follow their real-world values during startup.

In addition to this, investigation on the values shows that Rotorlib can't deal with the way we are handling the manipulation of individual engines, leading to a significant torque mismatch between the two engine. A temporary fix that has been found is to, while on the ground, gently raise collective to about 40% and then rapidly dump to 0%. This, when repeated enough times, occasionally causes the engine torque levels to synchronise.

In order to fix this, we must perform the same operations on each engine at the same time, while maintaining the appearance to the operator that they are being handled separately to maintain realism.

**Comment by SachaOropeza** [comment]
Really interesting.

**Comment by mattysmith22** [comment]
Example engine data from a startup has been gathered, which can be played back during startup. Engine MFD has been repaired, but will need fiddling with after the engine fix has been applied.

**Comment by mattysmith22** [comment]
Fixed by dd02a14047153
