### ISSUE TITLE
Aircraft animations reset can occur in-flight (MP)

### ISSUE THREAD

**Issue by mattysmith22** [SachaOropeza/AH64D-Project#50]
We have multiple reports of the PLT and CPG doors opening mid-flight in an MP scenario

**Comment by mattysmith22** [comment]
This is likely an issue with the `ah64d_init.sqf` file. It is run on init, and that opens the pilot door. It may be worth experimenting to find exactly what situations the [Init event handler](https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#Init) run in, as [`animate`](https://community.bistudio.com/wiki/animate) has global arguments and effect, meaning even if the apache isn't local to the machine running the init script, it will still have the intended effect.

It could be that having someone Join In Progress causes the init event handler to run locally on their machine?

**Comment by SachaOropeza** [comment]
Back in the days, it used to be linked to JIP players. Doors code are located in the init.

**Comment by mattysmith22** [comment]
Same thing happens to the rotor brake switch in flight. Good job that switch doesn't do anything!

**Comment by mattysmith22** [comment]
Should be able to easily fix by adding a global variable ON THE OBJECT using https://community.bistudio.com/wiki/setVariable (make sure you propagate out to other clients too) that is a boolean stating whether the object has been initialised. If it's nil, you initialise. If it's true, you do not. Something like `fza_ah64_unitInitialised`
