### ISSUE TITLE
CPG unable to enable/disable laser designation.

### ISSUE THREAD

**Issue by mattysmith22** [SachaOropeza/AH64D-Project#58]
Steps to reproduce (from fresh helicopter)

1) Enter the CPG seat
2) Perform the startup procedure so engines are idle
3) Switch to the WPN page on the left MFD
4) Click on "LRFD FIRST" selection on the MFD (R5)

Expected result:

* The gunner should get a "Laser Armed" chat message
* The laser should be on, and the weapon should be in the CPG's list of weapons.

Actual result:

Neither of the things mentioned in the expected result occur.

Thanks to "Lego Yoda" for reporting this!

**Comment by mattysmith22** [comment]
Low priority, can be mitigated

- ask your pilot to turn it on for you

**Comment by mattysmith22** [comment]
Sometimes this cannot be done by the pilot either due to locality issue. Boosting priority

**Comment by AngusLogan02** [comment]
Appears to be fixed, after slight testing, but should be tested more in multiplayer before closing.

**Comment by mattysmith22** [comment]
Advanced AI commands isn't a valid way of checking for locality issues. The issue is what machine is it being simulated on.

When you are flying with a CPG, the helicopter is local to the pilot except for the CPG turret which is local to the CPG. If you look at the docs for https://community.bistudio.com/wiki/addWeaponTurret there is a little blue "aL" in the top left. This means the argument (the helicopters turret) must be local to the machine that the line of code is being executed on.

**Comment by AngusLogan02** [comment]
Ah. My bad.
