### ISSUE TITLE
FCR may fail to run in some circumstances

### ISSUE THREAD

**Issue by mattysmith22** [SachaOropeza/AH64D-Project#67]
The FCR is only initialised for the first apache that is initialised, as it is in the `if (isNil "fza_ah64_fx_init") then {` section of `ah64d_init.sqf` meaning it is only run once.

In essence, this has been caused by that file being a mix of 3 types of code:
* Code that should run **only** once on a client machine
* Code that should run **only** once per machine at the start of the scenario
* Code that should run **only** once when a client connects to the scenario.

We should separate out these types, and break them out into their own functions to try and reduce the number of bugs following this pattern, like how the doors may randomly open due to JIPed players.

**Comment by SachaOropeza** [comment]
Nice finding buddy.

**Comment by mattysmith22** [comment]
Inits were redone as part of the CBA compat
