### ISSUE TITLE
Weapons may not be correctly synced between clients at times

### ISSUE THREAD

**Issue by Kill3rCat** [SachaOropeza/AH64D-Project#76]
Multiplayer testing with one other player on a dedicated server.

This issue occurred after a rough landing, where the aircraft was first 'healed' in Zeus, and then repaired/refueled through the arming menu. After the crash, the CPG player reported still having all missiles and nearly 1200 rounds of ammo on the WPN page, while the pilot whose client 'owned' the aircraft, saw 0 rounds of M230 ammo, and half of the Hellfires were missing.

After a re-arm through the arming menu, the CPG and pilot were seeing the same weapons again on the WPN page. However, the player in the CPG seat would fire Hellfires or the M230, but to other players, the weapons were not firing. Later in the same session, the CPG player would fire his M230 and not observe any impacts.

Edit: After both players had exited the vehicle, the pilot client observed the M230 seemingly firing on its own. Issue #75 had also occurred at this time, and the CPG player while on his client was no longer in the vehicle, to other players he was still inside in the CPG seat.

**Comment by mattysmith22** [comment]
Thank you for your feedback!

This one I have a definite idea for. Looking at the page, it uses the [`ammo`](https://community.bistudio.com/wiki/ammo) command to get the ammo count for the current magazine. Why on one client you didn't have the old loaded I don't know and will leave that to ARMA but my guess is the mag exists in both machines. If you are available for more testing on this, I would like to get more info on the problem.

If both you and your CPG have access to the debug console, please can I get the values of the following expressions reported? It is imperative I have this info for both seats, as it is an issue of desync between the two:
```sqf
(vehicle player) ammo "fza_m230"
```

```sqf
magazinesAmmoFull vehicle player
```

**Comment by mattysmith22** [comment]
Closed due to inactivity
