### ISSUE TITLE
Hidden targeting information when using this mod

### ISSUE THREAD

**Issue by mattysmith22** [SachaOropeza/AH64D-Project#82]
Targeting icons, like this:

![image](https://user-images.githubusercontent.com/9770674/92040107-1ef85c80-ed6e-11ea-939f-4ed9cbbe39b5.png)
(Credit Bohemia Community wiki)

Are disabled as soon as you install this mod. This is not optimal, as other vehicles rely on this for targeting and while it is good for us, it makes the vehicle much harder to use within units that would like to use it.

An optimal solution would allow for us to switch between having them shown or hidden depending on whether someone is in the Apache or not.

Thank you to Backles on our project discord for doing the difficult job of identifying that it was our mod that was causing this!

**Comment by mattysmith22** [comment]
At first we thought it was due to bad implementations of inheritance and config declarations overriding functionality in existing vanilla configs, but this was not the case. I cleaned all this up and that did not fix that (though it did cause a significant decrease in initialization times, so I will not be undoing that.)

After a couple hours of analysing config files I came across `fza_ah64_controls/uiconfig/monocle.hpp` and how it overrides `CfgInGameUI >> Cursor >> Targeting` to hide the information. This was done intentionally previously to hide the information in the Apache, but it unfortunately spills into other vehicles!

I spent a couple hours reading through the community wiki, couldn't find any info on there on how to do it, and couldn't seem to find anyone who knew how to disable it specifically for a single vehicle. I then looked into the arma 3 source code's scripts and configs to find references to `CfgInGameUI >> Cursor >> Targeting` icons and couldn't find any bar the help files, which leads me to believe this is a game engine implementation and not doing so via a script.

The only way to do it would be to somehow change the config so it only appears when outside the Apache.

**Comment by mattysmith22** [comment]
I then tried playing around with adding a variable like `fza_ah64_inApache` to the list of variables in the expression that declares the value of the [alpha channel](https://www.techopedia.com/definition/1945/alpha-channel) of the texture, but that didn't have any effect. From my deeper digging, it appears these expressions are not run constantly, but instead once at startup and the value evaluated then is the one evaluated for the rest of the game. That makes sense from a performance standpoint, but is unhelpful for this particular situation!

**Comment by mattysmith22** [comment]
My current idea is to still do this, but instead of evaluating it constantly how we'd like to right now, we could instead just leave it to user preference, "Would you like it always on or always off" and depending on that we can hide it or show it from startup.

I would recommend making this a default-off thing, if we keep it so that you have to specify that you *want* it to override global behaviour that seems more beneficial than just doing it!

For now it would be as simple as running this script to enable it:

```sqf
profileNamespace setVariable ["fza_ah64_hideTargeting", true];
saveProfileNamespace;
hint "Please reboot for these changes to come into effect!";
```

but once my CBA compat is done we could have it as a setting!

**Comment by SachaOropeza** [comment]
I guess we don't have any other choice if we don't want to impact other assets. I'm good with this idea. Once again, great job buddy. I assume this will be an additional option in the CBA settings tab, just like the button description rework when the click helper is hovering on some usable items.
