### ISSUE TITLE
C-scope missing FCR targets stored that are further than 8KM out

### ISSUE THREAD

**Issue by mattysmith22** [SachaOropeza/AH64D-Project#88]
The C-scope can only display targets that are less than 8km away, even if they are visible on the TSD and have been picked up by the FCR

Thanks to @AngusLogan02 for reporting this.

**Comment by mattysmith22** [comment]
This is likely to be due to the fact that the C-Scope pulls from `fza_ah64_dispfcrlist` rather than `fza_ah64_fcrlist`, which means it is filtered by type also, and is limited to what would be displayed on the FCR list.

Good find!

**Comment by Ollieollieolllie** [comment]
Fixed in my PR request
